import type { Metadata } from 'next';
import '../styles/globals.css';
import HeaderLayout from '../components/HeaderLayout';
import FooterLayout from '../components/FooterLayout';

export const metadata: Metadata = {
  title: 'Template Layout',
  description: 'Generated by lmd',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderLayout />
        <main>{children}</main>
        <FooterLayout />
      </body>
    </html>
  );
}
