import type { Metadata } from 'next';
import '../styles/globals.css';
import HeaderLayout from '../components/HeaderLayout';
import FooterLayout from '../components/FooterLayout';
import { ThemeProvider } from '../components/ThemeProviderShadCn';

export const metadata: Metadata = {
  title: 'Template Layout',
  description: 'Generated by lmd',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <HeaderLayout />
          <main>{children}</main>
          <FooterLayout />
        </ThemeProvider>
      </body>
    </html>
  );
}
