import type { Metadata } from 'next';
import fetchHelloWorldPage from './fetchHelloWorldPage';

export const metadata: Metadata = {
  title: 'HelloWorld - Template Next/Express project',
  description: 'Generated by lmd',
};

export default fetchHelloWorldPage;
