export const metadata: Metadata = {
  title: 'Database - Template Next/Express project',
  description: 'Generated by lmd',
};

import type { Metadata } from 'next';
export default function DatabaseLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
