name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint back-end code
        run: pnpm lint
        working-directory: ./back

      - name: Lint front-end code
        run: pnpm lint
        working-directory: ./front

      - name: Run type checks for back-end
        run: pnpm typecheck
        working-directory: ./back

      - name: Run type checks for front-end
        run: pnpm typecheck
        working-directory: ./front

      - name: Run back-end tests
        run: pnpm test
        working-directory: ./back

      - name: Run front-end tests
        run: pnpm test
        working-directory: ./front
